# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 79c610da8557ad490dbfa0c4ff23785291cd620314415b1d5711aa06ca37696e14fe68f313bbe948a16b413e0094025d16c967b8e17ff9e7181b4220c78a0e7b

test:
  secret_key_base: ff4b34bd60ddc511dbb2bb0bb5bcbdded2f158de3d9187f5ad6d990c55373694e7173e9442960e41295dfc2e6aac0765270f12a75b5b7a38cac43bb4f69be62f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
